# POST Tool List 
POST http://localhost:8000/mcp
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "tools/list",
  "params": []
}

# POST Terraform time
POST http://localhost:8000/mcp/tools/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/call",
  "params": {
    "name": "get_time",
    "arguments": {
      "tz": "UTC"
    }
  }
}

# POST Terraform Create configuration
POST http://localhost:8000/mcp/tools/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "tools/call",
  "params": {
    "name": "terraform-proxmox",
    "arguments": {
      "name": "web01",
      "cores": 4,
      "memory": 4096,
      "octet": "100",
      "image": "local:vztmpl\/debian-12-standard_12.12-1_amd64.tar.zst",
      "prefix": "192.188.200",
      "nameserver": "192.168.68.1",
      "vlan": 200,
      "bridge": "vmbr3"
    }
  }
}

# POST Terraform View file
POST http://localhost:8000/mcp/tools/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "terraform-view-file",
    "arguments": {
      "path": "platform/web01.tf"
    }
  }
}

# POST Terraform Apply file
POST http://localhost:8000/mcp/tools/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 5,
  "method": "tools/call",
  "params": {
    "name": "terraform-apply-vm",
    "arguments": {
      "path": "platform/web01.tf",
      "run_terraform": true
    }
  }
}

# POST Terraform Validate file
POST http://localhost:8000/mcp/tools/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 5,
  "method": "tools/call",
  "params": {
    "name": "terraform-validate-file",
    "arguments": {
      "path": "platform/web01.tf",
      "run_terraform": true
    }
  }
}

# POST Terraform destroy file 
POST http://localhost:8000/mcp/tool/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 8,
  "method": "tools/call",
  "params": {
    "name": "terraform-destroy-vm",
    "arguments": {
      "path": "platform/web01.tf"
    }
  }
}

# POST Check vm status
POST http://localhost:8000/mcp/tools/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 6,
  "method": "tools/call",
  "params": {
    "name": "proxmox-check-vm",
    "arguments": {
      "node": "proxmox",
      "vmid": 1010,
      "api_url": "https://proxmox.bebop.lan:8006/api2/json"
    }
  }
}

# POST Delete a VM 
POST http://localhost:8000/mcp/tool/call
Content-Type: application/json
{
  "jsonrpc": "2.0",
  "id": 7,
  "method": "tools/call",
  "params": {
    "name": "proxmox-delete-vm",
    "arguments": {
      "node": "proxmox",
      "vmid": 101,
      "api_url": "https://proxmox.bebop.lan:8006/api2/json"
    }
  }
}

